version: '3.8'

services:
  mosquitto:
    image: eclipse-mosquitto    
    container_name: mosquitto
    ports:
      - "1883:1883"
      - "9001:9001"
    networks:
      - mqtt-network
    volumes:
      - mosquitto_data:/mosquitto/data
      - mosquitto_log:/mosquitto/log
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf 

 
networks:
  mqtt-network:

volumes:
  mosquitto_data:
  mosquitto_log:
