version: '3.8'

services:
   spacemissionsubscribe:
    build:
      context: .  # Path to the directory containing Dockerfile for SpaceMissionSubscribe
    container_name: space_mission_excel
networks:
  mqtt-network:
    external: true  # Using an external network definition