version: '3.8'

services:
   spacemissionsubscribe:
    build:
      context: .  # Path to the directory containing Dockerfile for SpaceMissionSubscribe
    container_name: space_mission_publisher
    environment:
      - MQTT_BROKER_HOST=mosquitto  # Hostname of the Mosquitto broker container
networks:
  mqtt-network:
    external: true  # Using an external network definition